/**
 * VIP investment plans — amounts match platform spec (×3 per tier).
 * Daily profit = investment ÷ 3 (~33.33% per day).
 */
export const PACKAGES = [
  {
    id: "vip1",
    name: "VIP 1",
    shortName: "Vip1",
    level: 1,
    investment: 3,
    dailyProfit: 1,
    directPercent: 8,
    indirectPercent: 4,
    popular: false,
  },
  {
    id: "vip2",
    name: "VIP 2",
    shortName: "Vip2",
    level: 2,
    investment: 9,
    dailyProfit: 3,
    directPercent: 9,
    indirectPercent: 5,
    popular: false,
  },
  {
    id: "vip3",
    name: "VIP 3",
    shortName: "Vip3",
    level: 3,
    investment: 27,
    dailyProfit: 9,
    directPercent: 10,
    indirectPercent: 5,
    popular: true,
  },
  {
    id: "vip4",
    name: "VIP 4",
    shortName: "Vip4",
    level: 4,
    investment: 81,
    dailyProfit: 27,
    directPercent: 11,
    indirectPercent: 6,
    popular: false,
  },
  {
    id: "vip5",
    name: "VIP 5",
    shortName: "Vip5",
    level: 5,
    investment: 243,
    dailyProfit: 81,
    directPercent: 12,
    indirectPercent: 6,
    popular: false,
  },
  {
    id: "vip6",
    name: "VIP 6",
    shortName: "Vip6",
    level: 6,
    investment: 729,
    dailyProfit: 243,
    directPercent: 13,
    indirectPercent: 7,
    popular: false,
  },
  {
    id: "vip7",
    name: "VIP 7",
    shortName: "Vip7",
    level: 7,
    investment: 2187,
    dailyProfit: 729,
    directPercent: 14,
    indirectPercent: 7,
    popular: false,
  },
  {
    id: "vip8",
    name: "VIP 8",
    shortName: "Vip8",
    level: 8,
    investment: 6561,
    dailyProfit: 2187,
    directPercent: 15,
    indirectPercent: 8,
    popular: false,
  },
  {
    id: "vip9",
    name: "VIP 9",
    shortName: "Vip9",
    level: 9,
    investment: 19683,
    dailyProfit: 6561,
    directPercent: 16,
    indirectPercent: 8,
    popular: false,
  },
];
